mainUrl = https://v2.edoc.dev/login

Login = a.pravdiuk
Password = 23072000pravdykaG

Password.key = 23072000pravdyK

uiid = a20935dc-c598-4566-b7db-df0cd1cf9486
token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3OTE3OTU3MTcsImlhdCI6MTc5MTE5MDkxNywianRpIjoiOWY5NDhiMTEtYjc2OS00ZGVhLWIyMzAtM2MwY2I1ZjEzNDdiIiwic3ViIjoiYTIwOTM1ZGMtYzU5OC00NTY2LWI3ZGItZGYwY2QxY2Y5NDg2In0.TTtoy8zE-woMJCUQl3Sq0fmGOhYNUJmmXEkMWVUiGpA