mainUrl = https://sso.diia.org.ua/realms/diia-creatio-stage/protocol/saml?SAMLRequest=rZJRT8IwFIX%2FytL3rpMhsAZIEGIkAV0AffDFdOUCTboWezvUf283wMALTz725J7e7%2FS0j6LUez6q%2FM4s4LMC9NF0MiAfWZHddbtFm4q0ANq%2BS1Kapb0NbYleJyvStHVfbEj0Bg6VNQPSihMSTRErmBr0wvggJa2UJhlN2qukx9OEp513Ek3CBmWEb1w77%2FfIGUO08VopEVu3jSvBHAhdIqslKsMhTNNw6xbY3llvpdWs5ibRo3USGvgB2QiNUEPkAlEd4E%2FJT54HZdbKbAekcoZbgQq5ESUg95IvR%2FMZDyF4cRxC%2FrRa5TR%2FWa5INEIEVxOPrcGqBLcEd1ASXheziwweKykB8SrJaXJu16BZDXoSYjxItkQ7s1tlSPRdaoO86eI23jk%2FGfbrad48ubvw37aLcxIy%2FAfuPrtgOALt%2BXNYOp3kViv5E420tl%2FjusFQh3dVaIMNj7brTzf8BQ%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=LGRpHx55CwwRlzcaOPcmAOpi6kjEcZl8rUN3PRPtTrjRIeiXFaqjZMEjEfNT33VAPdFsinayzncCmr43P57FzKZ6Xv2CkS7Z04UdsbNssniNMJRSQ7n1T7MAp9rF0vU7SCOjUHQ2wbMx%2FEdE5TcBiLTmRRmk79HPMxSHbpheJrrv1VLho25eqIyCuumhmKtiMk8tHmOrAMWPHylXxdNWjYal7jZwKzEoTp0hudrLVOvy1EpMCYuZb2JQvqn5tjj5eyvy8qI5HlhCHCcwl7lfOLkX2ufWspTEP2onFtGjsbHtUpxHzzVyf9fPVoWV3hazXba9tIg9%2F2cBBHxpVQ0upQ%3D%3D#HomePage/StudioHomePage

Login.CRM = test_moderator
Password.CRM = tJar4vzqX2JZqXrm

user.test-l1 = test-l1
password.test-l1 = NsIdvt3OKuUgrhLF5Ugu

user.test-l2 = test-l2
password.test-l2 = 3X4tAHXyfZoOeA5X6knY

user.test-pm = test-pm
password.test-pm = EwuwNdvrnP92IzEDfnsY

user.test-tl = test-tl
password.test-tl = JUSsOqeZKiYHjixmot03

baseUrlAPI = https://stsuccess.diia.org.ua/ServiceModel/RegistryDownService.svc/CreateRegistryDownLog
apiKey = EQVd62oxNogd247bmnH3Db/Nh!lWcfwUrK46rDThCSldWUN-76OjjE-0E?3xBGg4-PO3Ko6JBPAhq8i1II=mO/MtWx7k6meI792GiIK5idOKduFsGqI?RPUwlGX7kXaBPF/il7RMLhiqLrkqDjetOS5GpkI?5H-0Be/5hkC4meAjaeHOKdsJSO1f?kyTC?WciXPjHaIs!IsEJ11WljhAWQRMyVT9PlNHOGRPh55wIDm6V6RTMAw9l6BzRRFxreQs